global using SqlSugar;
global using System.Data;
global using System.Text;
global using System.Reflection;
global using System.Linq.Expressions;
global using SqlSugar.Sharding.SqlServer;

global using WebAdmin.Entity.Base;
global using WebAdmin.Framework;
global using WebAdmin.Repositories;
global using WebAdmin.Infrastructure;
global using WebAdmin.Framework.Util;
global using WebAdmin.Repositories.Base;
global using WebAdmin.Infrastructure.Base;
global using WebAdmin.Domain.EntityBase;
global using WebAdmin.Framework.Providers;
global using WebAdmin.Framework.Extentions;
global using WebAdmin.Framework.Exceptions;
global using WebAdmin.Framework.Extentions.Exceptions;